# Generated by Django 5.0.4 on 2026-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('PAYOUT_HOLD', 'Payout Hold'), ('PAYOUT_REFUND', 'Payout Refund')], max_length=20),
        ),
    ]
